server:
  port: 8080
spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    #username: postgres
    #password: password
    #url: jdbc:postgresql://127.0.1.1:5432/arqui
    username: ${USERNAME_DB:postgres}
    password: ${PASSWORD:password}
    url: ${URL:jdbc:postgresql://127.0.1.1:5432/arqui}
  
  jpa:
    hibernate:
      ddl-auto: update 
      # Para crear una entidad si es que no existe en la bd

  application:
    name: currency-converter

# Configuramos springboot con keycloak
keycloak:
  realm: software
  auth-server-url: http://localhost:8008
  ssl-required: external
  resource: backend
  credentials:
    secret: bJ0drlN5kdWjBSJLRi6p0bd5xM5Qy7su
  use-resource-role-mappings: false
  security-constraints:
    - authRoles:
        - ADMIN
      security-collections:
        - name: SERVICIOS DEL ADMINISTRADOR
          patterns:
            - /api/currency/history
  # security-constraints[1]:
    - authRoles:
        - USER
      security-collections:
        - name: SERVICIOS DEL USUARIO
          patterns:
            - /api/currency/convert 
            